### ISSUE TITLE
缺少macro.c 

### ISSUE THREAD

**Issue by bbllmaster** [dnstzzx/usb-hid-bler#1]
`
CMake Error at C:/Users/general/esp/esp-idf/esp-idf-v4.4/tools/cmake/component.cmake:470 (add_library):
  Cannot find source file:

    D:/esp-idf/usb-hid-bler/main/macro.c
`

**Comment by dnstzzx** [comment]
这是还没提交的代码忘了在CMakeLists.txt上面删掉，在main/CMakeLists.txt删除就好

**Comment by dnstzzx** [comment]
macro.c已提交
